### ISSUE TITLE
helloworld_panda.py is not working - robot model is not loading

### ISSUE THREAD

**Issue by janisa9** [robotology-playground/pybullet-robot-envs#16]
I followed the provided installation instructions, but helloworld_panda.py is not working

It seems that it cannot load the robot model and crashes after ~30sec, 

`(ve_pybullet) janis@janis-MS-7B86:~/pybullet-robot-envs$ python3 pybullet_robot_envs/examples/helloworlds/helloworld_panda.py
/home/janis/pybullet-robot-envs/pybullet_robot_envs/examples/helloworlds
pybullet build time: Apr 21 2020 23:16:24
current_dir=/home/janis/pybullet-robot-envs/pybullet_robot_envs/envs/panda_envs
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=GeForce RTX 2070 SUPER/PCIe/SSE2
GL_VERSION=3.3.0 NVIDIA 435.21
GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
pthread_getconcurrency()=0
Version = 3.3.0 NVIDIA 435.21
Vendor = NVIDIA Corporation
Renderer = GeForce RTX 2070 SUPER/PCIe/SSE2
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
ven = NVIDIA Corporation
Segmentation fault (core dumped)
`

![Screenshot from 2020-06-02 22-41-41](https://user-images.githubusercontent.com/29726718/83563038-3b90b880-a523-11ea-8e38-b0355889a947.png)

Thus the test_panda_push_gym_env.py also doesn't load the model of the robot etc.
![Screenshot from 2020-06-02 22-54-44](https://user-images.githubusercontent.com/29726718/83563635-16e91080-a524-11ea-83b7-02f16061f30e.png)

I suppose there is something wrong with my installation, but I cannot figure out what exactly.

**Comment by eleramp** [comment]
I am sorry for the issue, I believe the problem is related to git-lfs that needs to be installed before cloning the repository, otherwise it mess-up the mesh files. Basically, the git lfs pull is not working properly in this case. I will try to figure out the problem.
So, please try to check your installation of  git-lfs by following the instruction [here](https://git-lfs.github.com/) and then clone again the repository.

**Comment by janisa9** [comment]
Thank you, I will take a look on that, I suppose I missed something with git lsf

**Comment by janisa9** [comment]
That was the case, thank you!
