### ISSUE TITLE
libraries missing in requirements.txt

### ISSUE THREAD

**Issue by xEnVrE** [robotology-playground/pybullet-robot-envs#17]
It seems that the library `seaborn` is required

https://github.com/robotology-playground/pybullet-robot-envs/blob/df346a27558a5b626723de5f40fc26a681d16add/pybullet_robot_envs/envs/utils.py#L6

and that `quaternion` is required here

https://github.com/robotology-playground/pybullet-robot-envs/blob/df346a27558a5b626723de5f40fc26a681d16add/pybullet_robot_envs/envs/icub_envs/icub_env_with_hands.py#L15

however, they are not listed in `requirements.txt`

https://github.com/robotology-playground/pybullet-robot-envs/blob/df346a27558a5b626723de5f40fc26a681d16add/requirements.txt#L1-L8

**Comment by eleramp** [comment]
Thanks!
