### ISSUE TITLE
Add instructions on how to run the code

### ISSUE THREAD

**Issue by giuliavezzani** [robotology-playground/pybullet-robot-envs#2]
Please @eleramp, could you update the README.md with detailed instructions on how to install the dependencies and how to run some examples?

I also suggest to include here just simple trainings and evaluations of the policies with one/two standard baselines (like the openai baselines) to show the correctness of the implemented environments. 
Then, the real implementation of new algorithms will be done in another repository.

**Comment by giuliavezzani** [comment]
@eleramp I tested your installation instructions. They are very well written, even if I encountered some problems.

Here are some suggestions to improve the instructions:

- In the [requirements.txt](https://github.com/robotology-playground/pybullet-robot-envs/blob/master/requirements.txt#L3) the required`matplotlib` version is `3.1.0` However, [this version requires `Python >=3.6`](https://matplotlib.org/3.1.0/users/installing.html#dependencies), while you say [here](https://github.com/robotology-playground/pybullet-robot-envs#prerequisites) that `pybullet-robot-envs` requires `Python>=3.5`. 
- [At the end of the installation instructions](https://github.com/robotology-playground/pybullet-robot-envs#installation), it'd be nice if you link or list the `id_envs` we designed, so that the user can immediately test them.
- I'm not able to run:
   ```
   $ python pybullet_robot_envs/examples/algos_baselines/train/icub_envs/train_deep_reaching.py
   ```
   I got the error: 
   ```
   TypeError: learn() got an unexpected keyword argument 'network'
   ```
  I think it's a matter of baselines version. Following your instructions I got version `0.1.5`.

- I'd be useful to add a section collecting the common issues. For example in my case, since I have both Python 2.7 and 3.5 installed I had to run everything with `pip3` and `python3`. Also, I got an error related to permission when running:
   ```
    pip3 install -r requirements.txt
   ```
   and 
   ```
    pip3 install -e .
    ```
    I solved running the following commands:
     ```
    pip3 install --user -r requirements.txt
   ```
   and 
   ```
    pip3 install  --user -e .
    ```

**Comment by eleramp** [comment]
@giuliavezzani thanks for your feedback! I updated the instruction trying to fix the issues you encountered. Please check if they are correct now and if you can finally run the script for training.

**Comment by giuliavezzani** [comment]
The new installation instructions go smoothly! Good job @eleramp :rocket:
 Let's leave this issue open, because @H2SO4T will need to make his code compatible with @eleramp's installation process and/or add other instructions to play with the Panda.

**Comment by giuliavezzani** [comment]
@eleramp I think the structure of this repo can be considered stable. Here are some suggestions:
- Please remember to add  in the README.md the description of the newly implemented environments (I was you added also the icub_push_env)
- Don't add other training example in this folder, the example with one openai baseline algorithm is enough.
- In the section **RL Examples** please add a link and a short description to you `robot-agents` project (which we need to move to `robotology-playground` too).

@H2SO4T, asap yu should align `panda` branch to `master`.

**Comment by giuliavezzani** [comment]
@H2SO4T please, once everything will be fixed, please add the instructions to launch your code in [the README.md](https://github.com/robotology-playground/pybullet-robot-envs/blob/master/README.md) following @eleramp's template (in every section named panda).

**Comment by giuliavezzani** [comment]
Well done guys @eleramp @H2SO4T
