### ISSUE TITLE
Can't get fls file, 'git lfs pull' is fault. Only 'git clone' is also fault.

### ISSUE THREAD

**Issue by zcZhangCheng** [robotology-playground/pybullet-robot-envs#31]
*Thanks for such beautiful code.*
*When I use git to download this repository, I get this kind of error：*

`>git lfs pull`

`batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`
`batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`
`batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`
`error: failed to fetch some objects from 'https://github.com/robotology-playground/pybullet-robot-envs.git/info/lfs'`

How can I solve this problem？ Thanks

**Comment by lornat75** [comment]
maybe a problem with git lfs, can you try again?

**Comment by zcZhangCheng** [comment]
Thanks for such a quick reply. I tried it a moment ago and it's no problem now. It may be a network or lfs error.
Thank you so much，@lornat75

**Comment by lornat75** [comment]
I actually increased the lfs quota! glad it solved the issue.
