### ISSUE TITLE
Uniform file names

### ISSUE THREAD

**Issue by giuliavezzani** [robotology-playground/pybullet-robot-envs#4]
@H2SO4T @eleramp once the structure will be ready, please make the name of the files uniform.

**Comment by giuliavezzani** [comment]
The structure of the repo is fine and the name coherent.
@H2SO4T just change [this file](https://github.com/robotology-playground/pybullet-robot-envs/tree/master/pybullet_robot_envs/examples/algos/test/baselines/panda_envs) name according to the policy followed [here](https://github.com/robotology-playground/pybullet-robot-envs/tree/master/pybullet_robot_envs/examples/algos/test/baselines/icub_envs).
After this fix, we can close the issue.

**Comment by H2SO4T** [comment]
Name changed!
