### ISSUE TITLE
Some problems after merge

### ISSUE THREAD

**Issue by giuliavezzani** [robotology-playground/pybullet-robot-envs#6]
@eleramp @H2SO4T after the last merge, we have two problems:

1. The environments are not registered properly. I think this is because we remove the import functions [here](https://github.com/robotology-playground/pybullet-robot-envs/blob/master/pybullet_robot_envs/envs/icub_envs/__init__.py) and [here](https://github.com/robotology-playground/pybullet-robot-envs/blob/master/pybullet_robot_envs/envs/panda_envs/__init__.py).
1. The [panda helloworld](https://github.com/robotology-playground/pybullet-robot-envs/blob/master/pybullet_robot_envs/examples/helloworlds/helloworld_panda.py) does not work since it does not find the robot model.

@eleramp could fixed problem no.1 both for panda and icub envs? 
@H2SO4T could you fixed problem no. 2?

**Comment by eleramp** [comment]
@giuliavezzani @H2SO4T commit 4dad7c4e48e79a41a89f0ebb463222f7eaf82f03 should have fixed the bug no.1, both for icub and panda environments.

**Comment by giuliavezzani** [comment]
@eleramp thanks a lot!

**Comment by H2SO4T** [comment]
@giuliavezzani fixed problem no. 2

**Comment by giuliavezzani** [comment]
@H2SO4T I cannot launch the `helloworld_panda.py`. If I launch:
```
python pybullet_robot_envs/examples/helloworlds/helloworld_panda.py 
```
I got the following error: 
```
URDF file 'panda_arm.urdf' not found
```

Please, make sure that we can launch the helloworld from the main folder.

**Comment by giuliavezzani** [comment]
Now it's fixed! Thanks @H2SO4!
