### ISSUE TITLE
File related to Panda need to be debugged

### ISSUE THREAD

**Issue by giuliavezzani** [robotology-playground/pybullet-robot-envs#7]
@H2SO4T I tried to launch the examples with the panda environments and I got some problems. I think they should be fixed in order to be properly launched after the merge with @eleramp's branch.

**Comment by H2SO4T** [comment]
Everything should be working now.

**Comment by giuliavezzani** [comment]
@H2SO4T If I try to launch the training or testing files, I get the following error:
```
ImportError: cannot import name 'logger'
```
