### ISSUE TITLE
Test environment script for Panda not working

### ISSUE THREAD

**Issue by maxime-petit** [robotology-playground/pybullet-robot-envs#8]
Dear all,

The script to test the Panda environment is not working with the current version and the following command line, from the readme:

> $ python pybullet_robot_envs/examples/test_envs/test_panda_push_gym_env.py

The problem is because of the **actionSpace** parameters of the pandaEnv function, L100 of ```panda_reach_gym_env.py```. The correct parameter name, from``` panda_env.py```, should be **action_space**. I fixed it by switching it in the ```panda_reach_gym_env.py```. The same has to be done for ```panda_push_gym_env.py``` (L101).

**Comment by H2SO4T** [comment]
Dear  @maxime-petit  thank you for your report, I'll fix it asap.
